---
apiVersion: v1
kind: Service
metadata:
  name: demo-node-app
  labels:
    app: demo-node-app
spec:
  type: LoadBalancer
  ports:
    - port: 1337
      targetPort: 3000
      protocol: TCP
      nodePort: 31110
  selector:
    app: demo-node-app
